import Head from "next/head";
import About from "./about";
import Blogs from './blogs';
import Tag from "./tag";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Shubolikhe Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Blogs/>
        <Tag/>
        <About />
      </main>
    </div>
  );
}
