import Head from "next/head";
import Navigation from "../components/navbar/navigation";
import About from "./about";
import Blogs from './blogs';
import Contact from "./contact";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Shubolikhe Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Blogs/>
        <About />
        <Contact />
      </main>
    </div>
  );
}
